# Generated by Django 3.2.3 on 2021-05-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
